#!/usr/bin/env python3
# -*- coding: utf-8 -*-

###################
#    little GUI to generate my slides
#    Copyright (C) 2025, 2026  PySlidesGenerator

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
###################

"""
little GUI to generate my slides
"""

__version__ = "1.0.0"
__author__ = "Maurice Lambert"
__author_email__ = "mauricelambert434@gmail.com"
__maintainer__ = "Maurice Lambert"
__maintainer_email__ = "mauricelambert434@gmail.com"
__description__ = """
little GUI to generate my slides
"""
__url__ = "https://github.com/mauricelambert/PySlidesGenerator"

# __all__ = []

__license__ = "GPL-3.0 License"
__copyright__ = """
PySlidesGenerator  Copyright (C) 2025, 2026  Maurice Lambert
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
"""
copyright = __copyright__
license = __license__

print(copyright)

from tkinter import (
    Menu,
    Frame,
    Label,
    Entry,
    Event,
    Listbox,
    Button,
    IntVar,
    StringVar,
    Toplevel,
    END,
    Radiobutton,
    Text,
    Tk,
    Canvas,
    Scrollbar,
    Misc,
)
from tkinter.messagebox import showerror, showinfo, showwarning, askokcancel
from tkinter.filedialog import askopenfilename, asksaveasfilename
from typing import Dict, List, Union
from json import dump, load, dumps
from string import Template
from html import escape

table_of_content_subtitle = Template(
    """<li><a href="#slide-${id}">${title}</a>
            <ul>
              ${titles}
            </ul>
          </li>"""
)

table_of_content_content = Template(
    '<li><a href="#slide-${id}">${title}</a></li>'
)

subtitle = Template(
    """<header>
        <img src="${icon}" alt="${icon_alt}" />
      </header>
      <article>
        <h2>${title}</h2>
      </article>"""
)

content = Template(
    """<header>
        <img src="${icon}" alt="${icon_alt}" />
        <h3>${title}</h3>
      </header>
      <article>
        <div class="text">
          ${text}
        </div>
        <img src="${image}" alt="${image_alt}" />
      </article>
      <aside>${aside}</aside>
      ${code_button}"""
)

content_image_left = Template(
    """<header>
        <img src="${icon}" alt="${icon_alt}" />
        <h3>${title}</h3>
      </header>
      <article class="image-left">
        <img src="${image}" alt="${image_alt}" />
        <div class="text">
          ${text}
        </div>
      </article>
      <aside>${aside}</aside>
      ${code_button}"""
)

content_image_only = Template(
    """<header>
        <img src="${icon}" alt="${icon_alt}" />
        <h3>${title}</h3>
      </header>
      <article class="image-only">
        <img src="${image}" alt="${image_alt}" />
      </article>
      <aside>${aside}</aside>"""
)

code_button_template = Template(
    """<button class="code-popup-btn"
    data-code="${code}"
    data-lang="${lang}"
    onclick="openCodePopup(this)"
    title="Show code">[&lt;/&gt;]</button>"""
)

code_popup_html = Template(
    """<div id="code-popup-overlay" style="display:none" onclick="if(event.target===this)closeCodePopup()">
  <div id="code-popup-box">
    <div id="code-popup-header">
      <span id="code-popup-lang"></span>
      <button onclick="closeCodePopup()">✕</button>
    </div>
    <pre id="code-popup-pre"><code id="code-popup-code"></code></pre>
  </div>
</div>"""
)

paragraph = Template("<p>${content}</p>")
list_element = Template("<li>${content}</li>")
ordered_list = Template(
    """<ol>
            ${list_content}
          </ol>"""
)
bullet_points = Template(
    """<ul>
            ${list_content}
          </ul>"""
)
section = Template(
    """<section id="slide-${index}" class="${class_name}">
      ${content}
    </section>"""
)

template = Template(
    """<!DOCTYPE html>
<!--
  Copyright (C) 2025, 2026 MauriceLambert

  This file is generated by PySlidesGenerator.

  PySlidesGenerator is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  PySlidesGenerator is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with PySlidesGenerator.  If not, see <https://www.gnu.org/licenses/>.
-->
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="index, follow">
  <meta name="description" content="${description}" />
  <meta name="keywords" content="${keywords}" />
  <meta name="author" content="${author}" />
  <title>${title}</title>
  <link rel="stylesheet" href="../styles.css" />
  <script defer src="../script.js"></script>
</head>
<body>
  <main>
    <section id="slide-1" class="title-slide">
      <div id="terminal-overlay">
        <pre id="terminal-output"></pre>
      </div>
      <header>
        <img src="${default_icon}" alt="${default_icon_alt}" />
      </header>
      <article>
        <h1>${title}</h1>
      </article>
    </section>
    <section class="table-content" id="slide-2">
      <header>
        <img src="${default_icon}" alt="${default_icon_alt}" />
      </header>
      <nav>
        <ul>
          ${table_of_content}
        </ul>
      </nav>
    </section>
    ${slides}
    <section class="timeline-slide content-slide" id="timeline-slide">
      <header>
        <img src="https://mauricelambert.github.io/MauriceLambert.png" alt="MauriceLambert icon" />
        <h3>My path, my passion: cybersecurity</h3>
      </header>
      <article>
        <div id="timeline-container"></div>
        <div id="timeline-progress"></div>
      </article>
    </section>
  </main>
  ${code_popup}
  <footer>
    <p><a href="https://www.gnu.org/licenses/">&copy; ${author}</a></p>
  </footer>
</body>
</html>"""
)

class ScrollableFrame(Frame):
    """Implements a scrollable frame."""

    def __init__(self, container: Misc, *args, **kwargs):
        super().__init__(container, *args, **kwargs)
        self.canvas = Canvas(self, bg="#2e2e2e", highlightthickness=0)
        self.scrollbar = Scrollbar(self, orient="vertical", command=self.canvas.yview)
        self.scrollable_frame = Frame(self.canvas, bg="#2e2e2e")

        self.scrollable_frame.bind("<Configure>", self._on_frame_configure)
        self.canvas.bind("<Configure>", self._on_canvas_configure)

        self.scrollable_window = self.canvas.create_window(
            (0, 0), window=self.scrollable_frame, anchor="nw"
        )
        self.canvas.configure(yscrollcommand=self.scrollbar.set)
        self.canvas.pack(side="left", fill="both", expand=True)
        self.scrollbar.pack(side="right", fill="y")

        self.scrollable_frame.bind("<Enter>", lambda e: self._bind_mousewheel())
        self.scrollable_frame.bind("<Leave>", lambda e: self._unbind_mousewheel())

    def _on_frame_configure(self, event: Event = None):
        self.canvas.configure(scrollregion=self.canvas.bbox("all"))

    def _on_canvas_configure(self, event: Event = None):
        self.canvas.itemconfig(self.scrollable_window)

    def _bind_mousewheel(self):
        self.canvas.bind_all(
            "<MouseWheel>",
            lambda e: self.canvas.yview_scroll(-1 * (e.delta // 120), "units"),
        )

    def _unbind_mousewheel(self):
        self.canvas.unbind_all("<MouseWheel>")

SLIDE_TYPES = [
    ("Part title",      "title"),
    ("Content (img right)", "content"),
    ("Content (img left)",  "content-left"),
    ("Image only",      "image-only"),
]

SLIDE_TYPE_LABELS = {k: lbl for lbl, k in SLIDE_TYPES}

class SlideGeneratorApp:
    """Main class: manages GUI, data and file I/O."""

    def __init__(self, root: Tk):
        self.root = root
        self.root.title("Slide Editor")
        self.root.geometry("800x600")
        self.data = {
            "title": "",
            "keywords": [],
            "description": "",
            "author": "Maurice Lambert",
            "default icon": "https://mauricelambert.github.io/MauriceLambert.png",
            "default icon alt": "MauriceLambert icon",
            "default aside": (
                'References: <a href="https://github.com/mauricelambert/">Github MauriceLambert</a>, '
                '<a href="https://mauricelambert.github.io/">MauriceLambert WebSite</a>.'
            ),
            "slides": [],
        }
        self.file_path = None
        self.export_path = None
        self.modified = False
        self.setup_ui()
        self.populate_fields()
        self.root.protocol("WM_DELETE_WINDOW", self.on_close)

    def setup_ui(self) -> None:
        """Create the main UI page."""
        self.root.configure(bg="#2e2e2e")

        menu_bar = Menu(self.root, bg="#2e2e2e", fg="#dd8a12")
        file_menu = Menu(menu_bar, tearoff=0, bg="#2e2e2e", fg="#dd8a12")
        file_menu.add_command(label="New (Ctrl+N)", command=self.new_file)
        file_menu.add_command(label="Open (Ctrl+O)", command=self.load_file)
        file_menu.add_command(label="Save (Ctrl+S)", command=self.save_file)
        file_menu.add_command(label="Generate (Ctrl+G)", command=self.generate_slides)
        file_menu.add_separator()
        file_menu.add_command(label="Exit (Ctrl+Q)", command=self.on_close)
        menu_bar.add_cascade(label="File", menu=file_menu)
        self.root.config(menu=menu_bar)

        scroll_frame = ScrollableFrame(self.root)
        scroll_frame.pack(fill="both", expand=True, pady=10)
        self.main_frame = scroll_frame.scrollable_frame

        self.entries = {}
        for field in [
            "title", "description", "author",
            "default icon", "default icon alt", "default aside",
        ]:
            Label(self.main_frame, text=field.capitalize(), bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")
            entry = Entry(self.main_frame, bg="#1e1e1e", fg="#dd8a12", insertbackground="#dd8a12")
            entry.pack(fill="x")
            entry.bind("<KeyRelease>", self.mark_modified)
            self.entries[field] = entry

        Label(self.main_frame, text="Keywords", bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")
        self.keyword_entries = []
        self.keyword_frame = Frame(self.main_frame, bg="#2e2e2e")
        self.keyword_frame.pack(fill="x", pady=5)
        self.add_keyword_entry()

        Label(self.main_frame, text="Slides", bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")
        self.slides_listbox = Listbox(self.main_frame, bg="#1e1e1e", fg="#dd8a12")
        self.slides_listbox.pack(fill="both", expand=True, pady=5)

        btn_frame = Frame(self.main_frame, bg="#2e2e2e")
        btn_frame.pack(fill="x")
        btn_cfg = dict(bg="#1e1e1e", fg="#dd8a12", activebackground="#444444", activeforeground="#dd8a12")
        Button(btn_frame, text="Add Slide",            command=self.add_slide_dialog,       **btn_cfg).pack(side="left", padx=5, pady=5)
        Button(btn_frame, text="Edit Slide",           command=self.edit_selected_slide,    **btn_cfg).pack(side="left", padx=5, pady=5)
        Button(btn_frame, text="Remove Selected Slide",command=self.remove_selected_slide,  **btn_cfg).pack(side="left", padx=5, pady=5)
        Button(btn_frame, text="Move Up",              command=self.move_slide_up,          **btn_cfg).pack(side="left", padx=5, pady=5)
        Button(btn_frame, text="Move Down",            command=self.move_slide_down,        **btn_cfg).pack(side="left", padx=5, pady=5)

        self.root.bind("<Control-s>", lambda e: self.save_file())
        self.root.bind("<Control-o>", lambda e: self.load_file())
        self.root.bind("<Control-n>", lambda e: self.new_file())
        self.root.bind("<Control-q>", lambda e: self.on_close())
        self.root.bind("<Control-g>", lambda e: self.generate_slides())

    def mark_modified(self, event: Event = None) -> None:
        self.modified = True

    def on_close(self) -> None:
        if self.modified:
            if not askokcancel("Unsaved Changes", "There are unsaved changes. Continue without saving?"):
                return
        self.root.destroy()

    def add_keyword_entry(self) -> None:
        entry = Entry(self.keyword_frame, bg="#1e1e1e", fg="#dd8a12", insertbackground="#dd8a12")
        entry.pack(fill="x", pady=2)
        entry.bind("<KeyRelease>", self.keyword_entry_updated)
        entry.bind("<KeyRelease>", self.mark_modified, add="+")
        self.keyword_entries.append(entry)

    def keyword_entry_updated(self, event: Event) -> None:
        for entry in self.keyword_entries:
            if not entry.get().strip():
                break
        else:
            self.add_keyword_entry()

    def new_file(self) -> None:
        self.file_path = None
        self.data = {
            "title": "", "keywords": [], "description": "",
            "author": "Maurice Lambert",
            "default icon": "https://mauricelambert.github.io/MauriceLambert.png",
            "default icon alt": "MauriceLambert icon",
            "default aside": (
                'References: <a href="https://github.com/mauricelambert/">Github MauriceLambert</a>, '
                '<a href="https://mauricelambert.github.io/">MauriceLambert WebSite</a>.'
            ),
            "slides": [],
        }
        for key in self.entries:
            self.entries[key].delete(0, END)
        for entry in self.keyword_entries:
            entry.destroy()
        self.keyword_entries.clear()
        self.add_keyword_entry()
        self.slides_listbox.delete(0, END)
        self.modified = False

    def load_file(self) -> None:
        path = askopenfilename(filetypes=[("JSON Files", "*.json")])
        if not path:
            return
        try:
            with open(path, "r") as f:
                self.data = load(f)
            self.populate_fields()
        except Exception as e:
            showerror("Error", f"Could not load file:\n{e}")
        else:
            self.file_path = path
            self.modified = False

    def save_file(self) -> None:
        if not self.file_path:
            path = asksaveasfilename(defaultextension=".json", filetypes=[("JSON Files", "*.json")])
            if not path:
                return
            self.file_path = path
        self.update_data_from_fields()
        try:
            with open(self.file_path, "w") as f:
                dump(self.data, f, indent=4)
        except Exception as e:
            showerror("Error", f"Could not save file:\n{e}")
        else:
            showinfo("Saved", "File saved successfully!")
            self.modified = False

    def generate_slides(self) -> None:
        """Generate the HTML file from current data."""
        if not self.export_path:
            path = asksaveasfilename(defaultextension=".html", filetypes=[("HTML Files", "*.html")])
            if not path:
                return
            self.export_path = path

        self.update_data_from_fields()

        slides_html = ""
        titles = ""
        last_subtitle = ""
        last_subtitle_index = 3
        table_of_content = ""

        for index, slide in enumerate(self.data["slides"]):
            slide_html_index = index + 3
            slide_type = slide["type"]
            icon_alt   = slide.get("icon alt", slide.get("icon", ""))
            image_alt  = slide.get("image alt", slide.get("image", ""))

            if slide_type in ("content", "content-left"):
                texts_html = ""
                for text in slide.get("texts", []):
                    if text["type"] == "p":
                        texts_html += paragraph.safe_substitute(content=text["content"])
                    else:
                        list_content = "".join(
                            list_element.safe_substitute(content=el)
                            for el in text["content"]
                        )
                        if text["type"] == "ul":
                            texts_html += bullet_points.safe_substitute(list_content=list_content)
                        elif text["type"] == "ol":
                            texts_html += ordered_list.safe_substitute(list_content=list_content)

                has_code = bool(slide.get("code", "").strip())
                btn_html = ""
                if has_code:
                    btn_html = code_button_template.safe_substitute(
                        code=escape(slide["code"]),
                        lang=slide.get("code lang", "")
                    )

                tpl = content_image_left if slide_type == "content-left" else content
                section_content = tpl.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=slide.get("title", ""),
                    text=texts_html,
                    aside=slide.get("aside", ""),
                    image=slide.get("image", ""),
                    image_alt=image_alt,
                    code_button=btn_html,
                )
                titles += table_of_content_content.safe_substitute(
                    title=slide["title"], id=slide_html_index
                )
                class_name = "content-slide"

            elif slide_type == "title":
                if last_subtitle:
                    table_of_content += table_of_content_subtitle.safe_substitute(
                        title=last_subtitle, titles=titles, id=last_subtitle_index
                    )
                    titles = ""
                last_subtitle = slide.get("title", "")
                last_subtitle_index = slide_html_index
                section_content = subtitle.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=last_subtitle,
                )
                class_name = "subtitle-slide"

            elif slide_type == "image-only":
                section_content = content_image_only.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=slide.get("title", ""),
                    image=slide.get("image", ""),
                    image_alt=image_alt,
                    aside=slide.get("aside", ""),
                )
                titles += table_of_content_content.safe_substitute(
                    title=slide.get("title", "(image)"), id=slide_html_index
                )
                class_name = "content-slide image-only-slide"

            else:
                continue

            slides_html += section.safe_substitute(
                index=str(slide_html_index),
                class_name=class_name,
                content=section_content,
            )

        if last_subtitle:
            table_of_content += table_of_content_subtitle.safe_substitute(
                title=last_subtitle, titles=titles, id=last_subtitle_index
            )

        file_content = template.safe_substitute(
            description=self.data.get("description", ""),
            keywords=", ".join(self.data.get("keywords", [])),
            title=self.data.get("title", ""),
            default_icon=self.data.get("default icon", ""),
            default_icon_alt=self.data.get("default icon alt", "MauriceLambert icon"),
            table_of_content=table_of_content,
            slides=slides_html,
            author=self.data.get("author", ""),
            code_popup=code_popup_html.safe_substitute(),
        )

        try:
            with open(self.export_path, "w", encoding="utf-8") as f:
                f.write(file_content)
        except Exception as e:
            showerror("Error", f"Could not generate file:\n{e}")
        else:
            showinfo("Generated", "File generated successfully!")

    def populate_fields(self) -> None:
        for key in self.entries:
            self.entries[key].delete(0, END)
            self.entries[key].insert(0, self.data.get(key, ""))
        for entry in self.keyword_entries:
            entry.destroy()
        self.keyword_entries.clear()
        for keyword in self.data.get("keywords", []):
            entry = Entry(self.keyword_frame, bg="#1e1e1e", fg="#dd8a12", insertbackground="#dd8a12")
            entry.insert(0, keyword)
            entry.pack(fill="x", pady=2)
            entry.bind("<KeyRelease>", self.keyword_entry_updated)
            entry.bind("<KeyRelease>", self.mark_modified, add="+")
            self.keyword_entries.append(entry)
        self.add_keyword_entry()
        self.slides_listbox.delete(0, END)
        for idx, slide in enumerate(self.data.get("slides", [])):
            label = SLIDE_TYPE_LABELS.get(slide["type"], slide["type"])
            title = slide.get("title", "")
            self.slides_listbox.insert(END, f"{idx+1}: [{label}] {title}")

    def update_data_from_fields(self) -> None:
        for key in self.entries:
            self.data[key] = self.entries[key].get()
        self.data["keywords"] = [
            e.get() for e in self.keyword_entries if e.get().strip()
        ]

    def add_slide_dialog(self) -> None:
        dialog = Toplevel(self.root)
        dialog.title("Add Slide")
        dialog.geometry("340x230")
        dialog.configure(bg="#2e2e2e")

        Label(dialog, text="Position", bg="#2e2e2e", fg="#dd8a12").pack(pady=5)
        position_var = IntVar(value=len(self.data["slides"]) + 1)
        Entry(dialog, textvariable=position_var, bg="#1e1e1e", fg="#dd8a12", insertbackground="#dd8a12").pack(fill="x", padx=10)

        Label(dialog, text="Type", bg="#2e2e2e", fg="#dd8a12").pack(pady=5)
        type_var = StringVar(value="content")
        type_frame = Frame(dialog, bg="#2e2e2e")
        type_frame.pack(pady=5)
        for label_text, value in SLIDE_TYPES:
            Radiobutton(
                type_frame, text=label_text, variable=type_var, value=value,
                bg="#2e2e2e", fg="#dd8a12", selectcolor="#1e1e1e",
                activebackground="#2e2e2e", activeforeground="#dd8a12",
            ).pack(anchor="w", padx=10)

        def submit() -> None:
            try:
                pos = int(position_var.get())
                if not (1 <= pos <= len(self.data["slides"]) + 1):
                    raise ValueError
            except ValueError:
                showerror("Invalid", "Position must be a valid number.")
                return

            slide_type = type_var.get()
            slide = {
                "type": slide_type,
                "icon": self.data["default icon"],
                "icon alt": self.data.get("default icon alt", ""),
                "title": "",
            }
            if slide_type in ("content", "content-left"):
                slide.update({
                    "aside": self.data["default aside"],
                    "image": "",
                    "image alt": "",
                    "texts": [],
                    "code": "",
                    "code lang": "",
                })
            elif slide_type == "image-only":
                slide.update({
                    "aside": self.data["default aside"],
                    "image": "",
                    "image alt": "",
                })

            self.update_data_from_fields()
            self.data["slides"].insert(pos - 1, slide)
            self.populate_fields()

            self.slides_listbox.select_clear(0, END)
            self.slides_listbox.select_set(pos - 1)
            self.slides_listbox.activate(pos - 1)

            dialog.destroy()
            self.modified = True

        Button(dialog, text="Add Slide", command=submit, bg="#1e1e1e", fg="#dd8a12",
               activebackground="#444444", activeforeground="#dd8a12").pack(pady=10)

    def edit_selected_slide(self) -> None:
        selection = self.slides_listbox.curselection()
        if not selection:
            showwarning("No selection", "Please select a slide to edit.")
            return
        self.open_slide_editor(self.data["slides"][selection[0]], selection[0])

    def remove_selected_slide(self) -> None:
        selection = self.slides_listbox.curselection()
        if not selection:
            showwarning("No selection", "Please select a slide to remove.")
            return
        del self.data["slides"][selection[0]]
        self.populate_fields()
        self.modified = True

    def move_slide_up(self) -> None:
        selection = self.slides_listbox.curselection()
        if not selection or selection[0] == 0:
            return
        i = selection[0]
        self.data["slides"][i - 1], self.data["slides"][i] = (
            self.data["slides"][i], self.data["slides"][i - 1]
        )
        self.populate_fields()
        self.slides_listbox.select_set(i - 1)
        self.modified = True

    def move_slide_down(self) -> None:
        selection = self.slides_listbox.curselection()
        if not selection or selection[0] == len(self.data["slides"]) - 1:
            return
        i = selection[0]
        self.data["slides"][i + 1], self.data["slides"][i] = (
            self.data["slides"][i], self.data["slides"][i + 1]
        )
        self.populate_fields()
        self.slides_listbox.select_set(i + 1)
        self.modified = True

    def open_slide_editor(
        self,
        slide: Dict[str, Union[List[Dict[str, str]], str]],
        index: int = None,
    ) -> None:
        """Manage slide edition GUI and data."""

        unsaved_slide = False

        def modify(event: Event = None) -> None:
            nonlocal unsaved_slide
            unsaved_slide = True

        dialog = Toplevel(self.root)
        dialog.title("Edit Slide")
        dialog.geometry("620x640")
        dialog.configure(bg="#2e2e2e")

        form_frame = Frame(dialog, bg="#2e2e2e")
        form_frame.pack(fill="both", expand=True, padx=10, pady=10)
        button_frame = Frame(dialog, bg="#2e2e2e")
        button_frame.pack(fill="x", padx=10, pady=10)

        slide_type = slide["type"]

        if slide_type in ("content", "content-left"):
            simple_fields = ("icon", "icon alt", "title", "image", "image alt", "aside")
        elif slide_type == "image-only":
            simple_fields = ("icon", "icon alt", "title", "image", "image alt", "aside")
        else:
            simple_fields = ("icon", "icon alt", "title")

        fields: Dict[str, Entry] = {}
        for field in simple_fields:
            Label(form_frame, text=field.capitalize(), bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")
            entry = Entry(form_frame, bg="#1e1e1e", fg="#dd8a12", insertbackground="#dd8a12")
            entry.insert(0, slide.get(field, ""))
            entry.bind("<KeyRelease>", modify)
            entry.pack(fill="x")
            fields[field] = entry

        scroll_frame = ScrollableFrame(form_frame)
        scroll_frame.pack(fill="both", expand=True, pady=10)
        text_container = scroll_frame.scrollable_frame

        texts: Dict[str, tuple] = {}

        if slide_type in ("content", "content-left"):
            Label(text_container, text="Texts", bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")

            def add_text_block(text_data: Dict[str, str] = None, _modify: bool = True):
                nonlocal unsaved_slide
                if _modify:
                    unsaved_slide = True

                text_type = StringVar(value=(text_data["type"] if text_data else "p"))
                frame = Frame(text_container, bg="#1e1e1e")
                frame.pack(fill="x", pady=5)

                type_frame = Frame(frame, bg="#1e1e1e")
                type_frame.pack(fill="x")
                for t_human, t_html in [("paragraph", "p"), ("bullet points", "ul"), ("ordered list", "ol")]:
                    Radiobutton(
                        type_frame, text=t_human, variable=text_type, value=t_html,
                        bg="#1e1e1e", fg="#dd8a12", selectcolor="#2e2e2e",
                    ).pack(side="left")

                content_frame = Frame(frame, bg="#2e2e2e")
                content_frame.pack(fill="both")
                content_widget = []

                def render_content_widget() -> None:
                    for w in content_frame.winfo_children():
                        w.destroy()
                    nonlocal content_widget
                    content_widget = []

                    if text_type.get() == "p":
                        text = Text(content_frame, height=3, bg="#1e1e1e", fg="#dd8a12", insertbackground="#dd8a12")
                        if text_data and text_data["type"] == "p":
                            text.insert("1.0", text_data["content"])
                        text.pack(fill="x")
                        content_widget = text
                    else:
                        entries = []
                        initial = (
                            text_data["content"]
                            if text_data and isinstance(text_data["content"], list)
                            else [""]
                        )
                        for item in initial:
                            e = Entry(content_frame, bg="#1e1e1e", fg="#dd8a12", insertbackground="#dd8a12")
                            e.insert(0, item)
                            e.pack(fill="x", pady=2)
                            entries.append(e)

                        def check_to_add_new(event: Event, last_entry: Entry) -> None:
                            if last_entry.get() and last_entry == entries[-1]:
                                ne = Entry(content_frame, bg="#1e1e1e", fg="#dd8a12", insertbackground="#dd8a12")
                                ne.pack(fill="x", pady=2)
                                ne.bind("<KeyRelease>", lambda ev: check_to_add_new(ev, ne))
                                entries.append(ne)
                            nonlocal unsaved_slide
                            unsaved_slide = event is not None

                        if entries:
                            entries[-1].bind("<KeyRelease>", lambda ev: check_to_add_new(ev, entries[-1]))
                        check_to_add_new(None, entries[-1])
                        content_widget = entries

                    texts[text_type._name] = (text_type, content_widget)

                text_type.trace_add("write", lambda *_: render_content_widget())
                render_content_widget()
                scroll_frame._on_frame_configure()
                scroll_frame._on_canvas_configure()

            for block in slide.get("texts", []):
                add_text_block(block, False)

            Button(button_frame, text="Add Text Block", command=add_text_block,
                   bg="#1e1e1e", fg="#dd8a12").pack(side="left", padx=5, pady=5)

            Label(text_container, text="Code (optional — opens in popup)",
                  bg="#2e2e2e", fg="#dd8a12").pack(anchor="w", pady=(10, 0))

            Label(text_container, text="Language (e.g. python, bash, c)",
                  bg="#2e2e2e", fg="#555555").pack(anchor="w")
            code_lang_entry = Entry(text_container, bg="#1e1e1e", fg="#dd8a12", insertbackground="#dd8a12")
            code_lang_entry.insert(0, slide.get("code lang", ""))
            code_lang_entry.bind("<KeyRelease>", modify)
            code_lang_entry.pack(fill="x", pady=2)

            Label(text_container, text="Code content", bg="#2e2e2e", fg="#555555").pack(anchor="w")
            code_text = Text(text_container, height=8, bg="#1e1e1e", fg="#00ff00",
                             insertbackground="#00ff00", font=("Courier New", 11))
            code_text.insert("1.0", slide.get("code", ""))
            code_text.bind("<KeyRelease>", modify)
            code_text.pack(fill="x", pady=2)

        def save() -> None:
            nonlocal unsaved_slide

            if slide_type in ("content", "content-left"):
                new_texts = []
                for t_type, cw in texts.values():
                    if t_type.get() == "p":
                        c = cw.get("1.0", "end").strip()
                        if c:
                            new_texts.append({"type": "p", "content": c})
                    else:
                        c = [e.get().strip() for e in cw if e.get().strip()]
                        if c:
                            new_texts.append({"type": t_type.get(), "content": c})
                slide["texts"] = new_texts

                slide["code"] = code_text.get("1.0", "end").strip()
                slide["code lang"] = code_lang_entry.get().strip()

            for field, entry in fields.items():
                slide[field] = entry.get().strip()

            self.populate_fields()
            self.modified = True
            unsaved_slide = False
            dialog.destroy()

        Button(button_frame, text="Save Slide", command=save,
               bg="#1e1e1e", fg="#dd8a12").pack(side="left", padx=5, pady=10)

        def on_close_dialog() -> None:
            if unsaved_slide:
                if not askokcancel("Unsaved Slide", "This slide has unsaved changes. Close anyway?"):
                    return
            dialog.destroy()

        dialog.protocol("WM_DELETE_WINDOW", on_close_dialog)

if __name__ == "__main__":
    root = Tk()
    app = SlideGeneratorApp(root)
    root.mainloop()