#!/usr/bin/env python3
# -*- coding: utf-8 -*-

###################
#    little GUI to generate my slides
#    Copyright (C) 2025, 2026  PySlidesGenerator

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
###################

"""
little GUI to generate my slides
"""

__version__ = "3.1.0"
__author__ = "Maurice Lambert"
__author_email__ = "mauricelambert434@gmail.com"
__maintainer__ = "Maurice Lambert"
__maintainer_email__ = "mauricelambert434@gmail.com"
__description__ = """
little GUI to generate my slides
"""
__url__ = "https://github.com/mauricelambert/PySlidesGenerator"

# __all__ = []

__license__ = "GPL-3.0 License"
__copyright__ = """
PySlidesGenerator  Copyright (C) 2025, 2026  Maurice Lambert
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
"""
copyright = __copyright__
license = __license__

print(copyright)

from tkinter import (
    Menu,
    Frame,
    Label,
    Entry,
    Event,
    Listbox,
    Button,
    IntVar,
    StringVar,
    Toplevel,
    END,
    Radiobutton,
    Text,
    Tk,
    Canvas,
    Scrollbar,
    Misc,
)
from tkinter.messagebox import showerror, showinfo, showwarning, askokcancel
from tkinter.filedialog import askopenfilename, asksaveasfilename
from os.path import join, dirname, splitext, basename, abspath
from tempfile import TemporaryDirectory
from webbrowser import open as webopen
from typing import Dict, List, Union
from json import dump, load, dumps
from string import Template
from shutil import copy2
from html import escape
from os import mkdir

notes_template = Template(
    """<!DOCTYPE html>
<!--
  Copyright (C) 2025, 2026 MauriceLambert

  This file is generated by PySlidesGenerator.

  PySlidesGenerator is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  PySlidesGenerator is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with PySlidesGenerator.  If not, see <https://www.gnu.org/licenses/>.
-->
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Speaker Notes</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=VT323&display=swap');

    :root {
      --green: #00ff41;
      --green-dim: #00aa2a;
      --green-ghost: rgba(0,255,65,0.07);
      --amber: #ffb300;
      --bg: #060d06;
      --bg2: #0b160b;
      --border: rgba(0,255,65,0.22);
      --font-mono: 'Share Tech Mono', 'Courier New', monospace;
      --font-display: 'VT323', monospace;
    }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    html, body {
      height: 100%;
      background: var(--bg);
      color: var(--green);
      font-family: var(--font-mono);
      overflow: hidden;
    }

    body::before {
      content: '';
      position: fixed; inset: 0;
      background: repeating-linear-gradient(
        0deg,
        transparent,
        transparent 2px,
        rgba(0,0,0,0.18) 2px,
        rgba(0,0,0,0.18) 4px
      );
      pointer-events: none;
      z-index: 1000;
    }

    body::after {
      content: '';
      position: fixed; inset: 0;
      background: radial-gradient(ellipse at center, transparent 55%, rgba(0,0,0,0.7) 100%);
      pointer-events: none;
      z-index: 999;
    }

    #app {
      display: grid;
      grid-template-rows: auto 1fr auto auto;
      height: 100vh;
      padding: 0;
    }

    #header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 8px 20px;
      border-bottom: 1px solid var(--border);
      background: var(--bg2);
      font-size: 11px;
      color: var(--green-dim);
      letter-spacing: 1px;
    }
    #header .logo {
      font-family: var(--font-display);
      font-size: 20px;
      color: var(--green);
      letter-spacing: 3px;
    }
    #header .status {
      display: flex; gap: 20px;
    }
    #header .status span { color: var(--green-dim); }
    #header .status strong { color: var(--green); }
    #sync-indicator {
      display: flex; align-items: center; gap: 6px;
      font-size: 11px;
    }
    #sync-dot {
      width: 7px; height: 7px; border-radius: 50%;
      background: var(--green-dim);
      transition: background 0.3s;
    }
    #sync-dot.active { background: var(--green); animation: pulse 0.4s ease-out; }
    @keyframes pulse { 0%{transform:scale(1)} 50%{transform:scale(1.8)} 100%{transform:scale(1)} }

    #prev-ghost {
      padding: 10px 24px 8px;
      border-bottom: 1px dashed rgba(0,255,65,0.12);
      min-height: 52px;
      display: flex;
      align-items: center;
      gap: 14px;
      opacity: 0.45;
      cursor: pointer;
      transition: opacity 0.2s;
    }
    #prev-ghost:hover { opacity: 0.65; }
    #prev-ghost .ghost-label {
      font-size: 10px; letter-spacing: 2px; color: var(--green-dim);
      white-space: nowrap;
      writing-mode: horizontal-tb;
    }
    #prev-ghost .ghost-title {
      font-family: var(--font-display);
      font-size: 18px;
      color: var(--green-dim);
      color: #a0e8a0;
      color: #c8ffc8;
      color: #e0ffe0;
      letter-spacing: 1px;
    }
    #prev-ghost .ghost-note {
      font-size: 11px; color: #3a7a3a;
      white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
      max-width: 400px;
    }

    #main {
      padding: 0 24px;
      overflow-y: auto;
      display: flex;
      flex-direction: column;
      gap: 0;
    }
    #main::-webkit-scrollbar { width: 4px; }
    #main::-webkit-scrollbar-track { background: transparent; }
    #main::-webkit-scrollbar-thumb { background: var(--border); border-radius: 2px; }

    #slide-header {
      padding: 18px 0 12px;
      border-bottom: 1px solid var(--border);
      margin-bottom: 16px;
      display: flex;
      align-items: baseline;
      gap: 16px;
    }
    #slide-counter {
      font-family: var(--font-display);
      font-size: 28px;
      color: var(--green-dim);
      white-space: nowrap;
    }
    #slide-title {
      font-family: var(--font-display);
      font-size: 38px;
      color: var(--green);
      letter-spacing: 2px;
      line-height: 1;
      word-break: break-word;
    }

    #notes-list {
      list-style: none;
      display: flex;
      flex-direction: column;
      gap: 0;
    }
    #notes-list li {
      display: flex;
      align-items: flex-start;
      gap: 12px;
      padding: 11px 0;
      border-bottom: 1px solid rgba(0,255,65,0.07);
      font-size: 15px;
      font-size: 17px;
      line-height: 1.5;
      color: #c8ffc8;
      color: #e8ffe8;
      animation: fadeIn 0.25s ease-out both;
    }
    #notes-list li:last-child { border-bottom: none; }
    #notes-list li .bullet {
      color: var(--green);
      font-size: 18px;
      margin-top: 1px;
      flex-shrink: 0;
      user-select: none;
    }
    @keyframes fadeIn {
      from { opacity: 0; transform: translateX(-8px); }
      to   { opacity: 1; transform: translateX(0); }
    }
    #notes-list li:nth-child(1) { animation-delay: 0.00s; }
    #notes-list li:nth-child(2) { animation-delay: 0.04s; }
    #notes-list li:nth-child(3) { animation-delay: 0.08s; }
    #notes-list li:nth-child(4) { animation-delay: 0.12s; }
    #notes-list li:nth-child(5) { animation-delay: 0.16s; }
    #notes-list li:nth-child(6) { animation-delay: 0.20s; }
    #notes-list li:nth-child(7) { animation-delay: 0.24s; }
    #notes-list li:nth-child(8) { animation-delay: 0.28s; }

    .no-notes {
      color: #2a5a2a;
      font-size: 13px;
      padding: 20px 0;
      font-style: italic;
    }

    #next-ghost {
      padding: 8px 24px 10px;
      border-top: 1px dashed rgba(0,255,65,0.12);
      min-height: 52px;
      display: flex;
      align-items: center;
      gap: 14px;
      opacity: 0.45;
      cursor: pointer;
      transition: opacity 0.2s;
    }
    #next-ghost:hover { opacity: 0.65; }
    #next-ghost .ghost-label {
      font-size: 10px; letter-spacing: 2px; color: var(--green-dim);
      white-space: nowrap;
    }
    #next-ghost .ghost-title {
      font-family: var(--font-display);
      font-size: 18px;
      color: var(--green-dim);
      color: #a0e8a0;
      color: #c8ffc8;
      color: #e0ffe0;
      letter-spacing: 1px;
    }
    #next-ghost .ghost-note {
      font-size: 11px; color: #3a7a3a;
      white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
      max-width: 400px;
    }

    #nav {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 10px 20px;
      border-top: 1px solid var(--border);
      background: var(--bg2);
      gap: 12px;
    }
    .nav-btn {
      background: transparent;
      border: 1px solid var(--border);
      color: var(--green);
      font-family: var(--font-mono);
      font-size: 12px;
      padding: 7px 18px;
      cursor: pointer;
      letter-spacing: 1px;
      transition: background 0.15s, border-color 0.15s;
      display: flex; align-items: center; gap: 8px;
    }
    .nav-btn:hover {
      background: var(--green-ghost);
      border-color: var(--green);
    }
    .nav-btn:active { transform: scale(0.97); }
    .nav-btn:disabled {
      opacity: 0.25; cursor: default;
      background: transparent !important;
    }

    #progress-bar-wrap {
      flex: 1;
      height: 3px;
      background: rgba(0,255,65,0.1);
      border-radius: 2px;
      overflow: hidden;
    }
    #progress-bar {
      height: 100%;
      background: var(--green);
      transition: width 0.3s ease;
    }

    #slide-position {
      font-size: 11px;
      color: var(--green-dim);
      white-space: nowrap;
      letter-spacing: 1px;
      min-width: 60px;
      text-align: right;
    }

    #flash {
      position: fixed; inset: 0;
      background: rgba(0,255,65,0.04);
      pointer-events: none;
      opacity: 0;
      z-index: 998;
      transition: opacity 0.05s;
    }
    #flash.on { opacity: 1; }

    #timers {
      display: flex;
      gap: 24px;
    }
    #timers .timer-block {
      display: flex;
      flex-direction: column;
      align-items: flex-end;
    }
    #timers .timer-label {
      font-size: 9px;
      letter-spacing: 2px;
      color: var(--green-dim);
    }
    #timers .timer-value {
      font-family: var(--font-display);
      font-size: 22px;
      color: var(--amber);
      letter-spacing: 2px;
      line-height: 1;
    }
  </style>
</head>
<body>
<div id="flash"></div>
<div id="app">

  <div id="header">
    <span class="logo">// SPEAKER NOTES</span>
    <div id="timers">
      <div class="timer-block">
        <span class="timer-label">FROM OPEN</span>
        <span class="timer-value" id="timer-open">00:00</span>
      </div>
      <div class="status">
        <span><strong id="hdr-title">─</strong></span>
      </div>
      <div class="timer-block">
        <span class="timer-label">FROM START</span>
        <span class="timer-value" id="timer-start">──:──</span>
      </div>
    </div>
    <div id="sync-indicator">
      <div id="sync-dot"></div>
      <span id="sync-label">SYNC OFF</span>
    </div>
  </div>

  <div id="next-ghost" onclick="navigate(1)">
    <span class="ghost-label">NEXT ▶</span>
    <span class="ghost-title" id="next-title">─</span>
    <span class="ghost-note" id="next-note"></span>
  </div>

  <div id="main">
    <div id="slide-header">
      <span id="slide-counter">01</span>
      <span id="slide-title">─</span>
    </div>
    <ul id="notes-list"></ul>
  </div>

  <div id="prev-ghost" onclick="navigate(-1)">
    <span class="ghost-label">◀ PREV</span>
    <span class="ghost-title" id="prev-title">─</span>
    <span class="ghost-note" id="prev-note"></span>
  </div>

  <div id="nav">
    <button class="nav-btn" id="btn-prev" onclick="navigate(-1)">◀ PREVIOUS</button>
    <div id="progress-bar-wrap"><div id="progress-bar"></div></div>
    <span id="slide-position">1 / 1</span>
    <button class="nav-btn" id="btn-next" onclick="navigate(1)">NEXT ▶</button>
  </div>

</div>

<script>
// window.SLIDES_NOTES = notes_interpolation;
const SLIDES = window.SLIDES_NOTES || ${notes};

let current = 0;
const total  = SLIDES.length;
let syncEnabled = false;

const timeOpen  = Date.now();
let   timeStart = null;

function formatTime(ms) {
  const s   = Math.floor(ms / 1000);
  const min = Math.floor(s / 60).toString().padStart(2, '0');
  const sec = (s % 60).toString().padStart(2, '0');
  return min + ':' + sec;
}

setInterval(() => {
  document.getElementById('timer-open').textContent  = formatTime(Date.now() - timeOpen);
  document.getElementById('timer-start').textContent =
    timeStart ? formatTime(Date.now() - timeStart) : '──:──';
}, 500);

const bc = new BroadcastChannel('presentation_sync');

bc.onmessage = (e) => {
  if (!syncEnabled) return;
  if (e.data?.type === 'slide_change' && typeof e.data.index === 'number') {
    if (e.data.index !== current) {
      current = Math.max(0, Math.min(total - 1, e.data.index));
      render(false);
      flashSync();
    }
  }
};

function broadcast(index) {
  if (syncEnabled) {
    bc.postMessage({ type: 'slide_change', index });
  }
}

document.getElementById('sync-indicator').addEventListener('click', () => {
  syncEnabled = !syncEnabled;
  document.getElementById('sync-dot').style.background   = syncEnabled ? 'var(--green)' : 'var(--green-dim)';
  document.getElementById('sync-label').textContent      = syncEnabled ? 'SYNC ON' : 'SYNC OFF';
  if (syncEnabled) broadcast(current);
});

function flashSync() {
  const dot = document.getElementById('sync-dot');
  dot.classList.add('active');
  setTimeout(() => dot.classList.remove('active'), 400);
}

function navigate(dir) {
  const next = current + dir;
  if (next < 0 || next >= total) return;
  current = next;
  if (current >= 1 && timeStart === null) timeStart = Date.now();
  render(true);
}

function render(shouldBroadcast = true) {
  const slide = SLIDES[current];
  const prev  = current > 0          ? SLIDES[current - 1] : null;
  const next  = current < total - 1  ? SLIDES[current + 1] : null;

  document.getElementById('hdr-title').textContent    = slide.title;
  document.getElementById('slide-counter').textContent = String(current + 1).padStart(2, '0');
  document.getElementById('slide-title').textContent  = slide.title;

  const ul = document.getElementById('notes-list');
  ul.innerHTML = '';
  if (slide.notes && slide.notes.length > 0) {
    slide.notes.forEach(note => {
      const li = document.createElement('li');
      li.innerHTML = `<span class="bullet">▸</span><span>${escHtml(note)}</span>`;
      ul.appendChild(li);
    });
  } else {
    ul.innerHTML = '<li class="no-notes">// no notes for this slide</li>';
  }

  const prevGhost = document.getElementById('prev-ghost');
  document.getElementById('prev-title').textContent = prev ? prev.title : '─';
  document.getElementById('prev-note').textContent  = prev && prev.notes[0] ? prev.notes[0] : '';
  prevGhost.style.visibility = prev ? 'visible' : 'hidden';

  const nextGhost = document.getElementById('next-ghost');
  document.getElementById('next-title').textContent = next ? next.title : '─';
  document.getElementById('next-note').textContent  = next && next.notes[0] ? next.notes[0] : '';
  nextGhost.style.visibility = next ? 'visible' : 'hidden';

  document.getElementById('btn-prev').disabled = current === 0;
  document.getElementById('btn-next').disabled = current === total - 1;

  const pct = total > 1 ? (current / (total - 1)) * 100 : 100;
  document.getElementById('progress-bar').style.width = pct + '%';
  document.getElementById('slide-position').textContent = (current + 1).toString() + " / " + String(total);

  document.getElementById('main').scrollTop = 0;

  const f = document.getElementById('flash');
  f.classList.add('on');
  setTimeout(() => f.classList.remove('on'), 80);

  if (shouldBroadcast) broadcast(current);
}

function escHtml(str) {
  return str.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
}

document.addEventListener('keydown', e => {
  if (e.key === 'ArrowRight' || e.key === 'ArrowDown' || e.key === ' ') {
    e.preventDefault(); navigate(1);
  } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
    e.preventDefault(); navigate(-1);
  } else if (e.key === 's' || e.key === 'S') {
    document.getElementById('sync-indicator').click();
  }
});

render(false);
</script>
</body>
</html>"""
)

table_of_content_subtitle = Template(
    """<li><a href="#slide-${id}">${title}</a>
            <ul>
              ${titles}
            </ul>
          </li>"""
)

table_of_content_content = Template(
    '<li><a href="#slide-${id}">${title}</a></li>'
)

subtitle = Template(
    """<header>
        <img src="${icon}" alt="${icon_alt}" />
      </header>
      <article>
        <h2>${title}</h2>
      </article>"""
)

content = Template(
    """<header>
        <img src="${icon}" alt="${icon_alt}" />
        <h3>${title}</h3>
      </header>
      <article>
        <div class="text">
          ${text}
        </div>
        <img src="${image}" alt="${image_alt}" />
      </article>
      <aside>${aside}</aside>
      ${code_button}"""
)

content_image_left = Template(
    """<header>
        <img src="${icon}" alt="${icon_alt}" />
        <h3>${title}</h3>
      </header>
      <article class="image-left">
        <img src="${image}" alt="${image_alt}" />
        <div class="text">
          ${text}
        </div>
      </article>
      <aside>${aside}</aside>
      ${code_button}"""
)

content_image_only = Template(
    """<header>
        <img src="${icon}" alt="${icon_alt}" />
        <h3>${title}</h3>
      </header>
      <article class="image-only">
        <img src="${image}" alt="${image_alt}" />
      </article>
      <aside>${aside}</aside>"""
)

cards_content = Template(
    """<header>
        <img src="${icon}" alt="${icon_alt}" />
        <h3>${title}</h3>
      </header>

      <article class="cards-container">
        ${cards}
      </article>

      <aside>${aside}</aside>"""
)

card_template = Template(
    """<div class="card">
        <h4>${title}</h4>
        <p>${content}</p>
      </div>"""
)

code_button_template = Template(
    """<button class="code-popup-btn"
    data-code="${code}"
    data-lang="${lang}"
    onclick="openCodePopup(this)"
    title="Show code">[&lt;/&gt;]</button>"""
)

code_popup_html = Template(
    """<div id="code-popup-overlay" style="display:none" onclick="if(event.target===this)closeCodePopup()">
  <div id="code-popup-box">
    <div id="code-popup-header">
      <span id="code-popup-lang"></span>
      <button onclick="closeCodePopup()">✕</button>
    </div>
    <pre id="code-popup-pre"><code id="code-popup-code"></code></pre>
  </div>
</div>"""
)

paragraph = Template("<p>${content}</p>")
list_element = Template("<li>${content}</li>")
ordered_list = Template(
    """<ol>
            ${list_content}
          </ol>"""
)
bullet_points = Template(
    """<ul>
            ${list_content}
          </ul>"""
)
section = Template(
    """<section id="slide-${index}" class="${class_name}">
      ${content}
    </section>"""
)

template = Template(
    """<!DOCTYPE html>
<!--
  Copyright (C) 2025, 2026 MauriceLambert

  This file is generated by PySlidesGenerator.

  PySlidesGenerator is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  PySlidesGenerator is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with PySlidesGenerator.  If not, see <https://www.gnu.org/licenses/>.
-->
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="index, follow">
  <meta name="description" content="${description}" />
  <meta name="keywords" content="${keywords}" />
  <meta name="author" content="${author}" />
  <title>${title}</title>
  <link rel="stylesheet" href="../styles.css" />
  <script defer src="../script.js"></script>
</head>
<body>
  <main>
    <section id="slide-1" class="title-slide">
      <div id="terminal-overlay">
        <pre id="terminal-output"></pre>
      </div>
      <header>
        <img src="${default_icon}" alt="${default_icon_alt}" />
      </header>
      <article>
        <h1>${title}</h1>
      </article>
    </section>
    <section class="table-content" id="slide-2">
      <header>
        <img src="${default_icon}" alt="${default_icon_alt}" />
      </header>
      <nav>
        <ul>
          ${table_of_content}
        </ul>
      </nav>
    </section>
    ${slides}
    <section class="timeline-slide content-slide" id="timeline-slide">
      <header>
        <img src="https://mauricelambert.github.io/MauriceLambert.png" alt="Metallic serpent dragon logo in red to purple gradient symbolizing offensive power, high quality, mythic strength and Python-inspired security defense" />
        <h3>My path, my passion: cybersecurity</h3>
      </header>
      <article>
        <div id="timeline-container"></div>
        <div id="timeline-progress"></div>
      </article>
    </section>
  </main>
  ${code_popup}
  <footer>
    <p><a href="https://www.gnu.org/licenses/">&copy; ${author}</a></p>
  </footer>
</body>
</html>"""
)

class ScrollableFrame(Frame):
    """Implements a scrollable frame."""

    def __init__(self, container: Misc, *args, **kwargs):
        super().__init__(container, *args, **kwargs)
        self.canvas = Canvas(self, bg="#2e2e2e", highlightthickness=0)
        self.scrollbar = Scrollbar(self, orient="vertical", command=self.canvas.yview)
        self.scrollable_frame = Frame(self.canvas, bg="#2e2e2e")

        self.scrollable_frame.bind("<Configure>", self._on_frame_configure)
        self.canvas.bind("<Configure>", self._on_canvas_configure)

        self.scrollable_window = self.canvas.create_window(
            (0, 0), window=self.scrollable_frame, anchor="nw"
        )
        self.canvas.configure(yscrollcommand=self.scrollbar.set)
        self.canvas.pack(side="left", fill="both", expand=True)
        self.scrollbar.pack(side="right", fill="y")

        self.scrollable_frame.bind("<Enter>", lambda e: self._bind_mousewheel())
        self.scrollable_frame.bind("<Leave>", lambda e: self._unbind_mousewheel())

    def _on_frame_configure(self, event: Event = None):
        self.canvas.configure(scrollregion=self.canvas.bbox("all"))

    def _on_canvas_configure(self, event: Event = None):
        self.canvas.itemconfig(self.scrollable_window)

    def _bind_mousewheel(self):
        self.canvas.bind_all(
            "<MouseWheel>",
            lambda e: self.canvas.yview_scroll(-1 * (e.delta // 120), "units"),
        )

    def _unbind_mousewheel(self):
        self.canvas.unbind_all("<MouseWheel>")

SLIDE_TYPES = [
    ("Part title",          "title"),
    ("Content (img right)", "content"),
    ("Content (img left)",  "content-left"),
    ("Image only",          "image-only"),
    ("Cards",               "cards"),
]

SLIDE_TYPE_LABELS = {k: lbl for lbl, k in SLIDE_TYPES}
WORDS_PER_MINUTE = 110

class SlideGeneratorApp:
    """Main class: manages GUI, data and file I/O."""

    def __init__(self, root: Tk):
        self.filtered_slide_indexes = []
        self.section_indexes = []
        self.root = root
        self.root.title("Slide Editor")
        self.root.geometry("800x600")
        self.data = self.get_default_data()
        self.file_path = None
        self.export_path = None
        self.modified = False
        self.setup_ui()
        self.populate_fields()
        self.root.protocol("WM_DELETE_WINDOW", self.on_close)

    @staticmethod
    def get_default_data() -> Dict[str, str]:
        return {
            "title": "",
            "keywords": [],
            "description": "",
            "author": "Maurice Lambert",
            "default icon": "https://mauricelambert.github.io/MauriceLambert.png",
            "default icon alt": (
                "Metallic serpent dragon logo in red to purple gradient symbolizing offensive power,"
                " high quality, mythic strength and Python-inspired security defense"
            ),
            "default aside": (
                'References: <a href="https://github.com/mauricelambert/">Github MauriceLambert</a>, '
                '<a href="https://mauricelambert.github.io/">MauriceLambert WebSite</a>.'
            ),
            "slides": [],
        }

    def setup_ui(self) -> None:
        """Create the main UI page."""
        self.root.configure(bg="#2e2e2e")

        menu_bar = Menu(self.root, bg="#2e2e2e", fg="#dd8a12")
        file_menu = Menu(menu_bar, tearoff=0, bg="#2e2e2e", fg="#dd8a12")
        file_menu.add_command(label="New (Ctrl+N)", command=self.new_file)
        file_menu.add_command(label="Open (Ctrl+O)", command=self.load_file)
        file_menu.add_command(label="Save (Ctrl+S)", command=self.save_file)
        file_menu.add_command(label="Generate (Ctrl+G)", command=self.generate_slides)
        file_menu.add_command(label="Validate (Ctrl+V)", command=self.validate_slides)
        file_menu.add_separator()
        file_menu.add_command(label="Exit (Ctrl+Q)", command=self.on_close)
        menu_bar.add_cascade(label="File", menu=file_menu)
        self.root.config(menu=menu_bar)

        main_container = Frame(self.root, bg="#2e2e2e")
        main_container.pack(fill="both", expand=True)

        left_panel = Frame(main_container, bg="#2e2e2e")
        left_panel.pack(side="left", fill="both", expand=True)

        right_panel = Frame(main_container, bg="#2e2e2e")
        right_panel.pack(side="right", fill="y")

        scroll_frame = ScrollableFrame(left_panel)
        scroll_frame.pack(fill="both", expand=True, pady=10)
        self.main_frame = scroll_frame.scrollable_frame

        self.entries = {}
        for field in [
            "title", "description", "author",
            "default icon", "default icon alt", "default aside",
        ]:
            Label(self.main_frame, text=field.capitalize(), bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")
            entry = Entry(self.main_frame, bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e", insertbackground="#dd8a12")
            entry.pack(fill="x")
            entry.bind("<KeyRelease>", self.mark_modified)
            self.entries[field] = entry
            if field == "title":
                entry.bind("<KeyRelease>", lambda e: self.update_title(), add="+")

        Label(self.main_frame, text="Keywords", bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")
        self.keyword_entries = []
        self.keyword_frame = Frame(self.main_frame, bg="#2e2e2e")
        self.keyword_frame.pack(fill="x", pady=5)
        self.add_keyword_entry()

        Label(self.main_frame, text="Search slides", bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")
        self.slide_search_var = StringVar()
        self.slide_search_var.trace_add("write", self.filter_slides)
        self.slide_search_entry = Entry(self.main_frame, textvariable=self.slide_search_var,
            bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e", insertbackground="#dd8a12"
        )
        self.slide_search_entry.pack(fill="x", pady=3)

        self.progress_label = Label(self.main_frame, text="Progress: 0% | 0m", bg="#2e2e2e", fg="#dd8a12", font=("Courier New", 10))
        self.progress_label.pack(anchor="w", pady=(5, 2))

        # slides_container = Frame(self.main_frame, bg="#2e2e2e")
        # slides_container.pack(fill="both", expand=True, pady=5)
        Label(right_panel, text="Slides", bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")
        self.slides_listbox = Listbox(right_panel, bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e")
        self.slides_listbox.pack(fill="both", expand=True, padx=5, pady=5)

        Label(self.main_frame, text="Sections", bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")
        self.section_listbox = Listbox(self.main_frame, width=28, bg="#151515", fg="#66ff66", selectbackground="#66ff66", selectforeground="#151515", exportselection=False)
        self.section_listbox.pack(fill="x", pady=5)

        btn_frame = Frame(self.main_frame, bg="#2e2e2e")
        btn_frame.pack(fill="x")
        btn_cfg = dict(bg="#1e1e1e", fg="#dd8a12", activebackground="#444444", activeforeground="#dd8a12")
        Button(btn_frame, text="Add Slide",            command=self.add_slide_dialog,       **btn_cfg).pack(side="left", padx=5, pady=5)
        Button(btn_frame, text="Edit Slide",           command=self.edit_selected_slide,    **btn_cfg).pack(side="left", padx=5, pady=5)
        Button(btn_frame, text="Remove Selected Slide",command=self.remove_selected_slide,  **btn_cfg).pack(side="left", padx=5, pady=5)
        Button(btn_frame, text="Move Up",              command=self.move_slide_up,          **btn_cfg).pack(side="left", padx=5, pady=5)
        Button(btn_frame, text="Move Down",            command=self.move_slide_down,        **btn_cfg).pack(side="left", padx=5, pady=5)
        Button(btn_frame, text="Preview",              command=self.preview_html,           **btn_cfg).pack(side="left", padx=5, pady=5)

        self.root.bind("<Control-s>", lambda e: self.save_file())
        self.root.bind("<Control-o>", lambda e: self.load_file())
        self.root.bind("<Control-n>", lambda e: self.new_file())
        self.root.bind("<Control-q>", lambda e: self.on_close())
        self.root.bind("<Control-g>", lambda e: self.generate_slides())
        self.root.bind("<Control-v>", lambda e: self.validate_slides())

        self.section_listbox.bind("<Double-Button-1>", self.jump_to_section)
        self.section_listbox.bind("<<ListboxSelect>>", self.jump_to_section)
        self.slides_listbox.bind("<<ListboxSelect>>", lambda e: self.sync_section_selection())
        self.slides_listbox.bind("<Double-Button-1>", lambda e: self.edit_selected_slide())
        self.slides_listbox.bind("<Return>", lambda e: self.edit_selected_slide())

        self.slides_listbox.bind("<Up>", self.on_slide_list_up)
        self.slides_listbox.bind("<Down>", self.on_slide_list_down)

    def build_html(self) -> str:
        self.update_data_from_fields()

        slides_html = ""
        titles = ""
        last_subtitle = ""
        last_subtitle_index = 3
        table_of_content = ""

        for index, slide in enumerate(self.data["slides"]):
            slide_html_index = index + 3
            slide_type = slide["type"]

            icon_alt = slide.get("icon alt", self.data.get("default icon alt", ""))
            image_alt = slide.get("image alt", "")

            if slide_type in ("content", "content-left"):
                texts_html = ""
                for text in slide.get("texts", []):
                    if text["type"] == "p":
                        texts_html += paragraph.safe_substitute(content=text["content"])
                    else:
                        list_content = "".join(
                            list_element.safe_substitute(content=el)
                            for el in text["content"]
                        )
                        if text["type"] == "ul":
                            texts_html += bullet_points.safe_substitute(list_content=list_content)
                        elif text["type"] == "ol":
                            texts_html += ordered_list.safe_substitute(list_content=list_content)

                has_code = bool(slide.get("code", "").strip())
                btn_html = ""
                if has_code:
                    btn_html = code_button_template.safe_substitute(
                        code=escape(slide["code"]),
                        lang=slide.get("code lang", "")
                    )

                tpl = content_image_left if slide_type == "content-left" else content
                section_content = tpl.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=slide.get("title", ""),
                    text=texts_html,
                    aside=slide.get("aside", ""),
                    image=slide.get("image", ""),
                    image_alt=image_alt,
                    code_button=btn_html,
                )
                titles += table_of_content_content.safe_substitute(
                    title=slide["title"], id=slide_html_index
                )
                class_name = "content-slide"

            elif slide_type == "title":
                if last_subtitle:
                    table_of_content += table_of_content_subtitle.safe_substitute(
                        title=last_subtitle,
                        titles=titles,
                        id=last_subtitle_index
                    )
                    titles = ""

                last_subtitle = slide.get("title", "")
                last_subtitle_index = slide_html_index

                section_content = subtitle.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=last_subtitle,
                )
                class_name = "subtitle-slide"

            elif slide_type == "image-only":
                section_content = content_image_only.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=slide.get("title", ""),
                    image=slide.get("image", ""),
                    image_alt=image_alt,
                    aside=slide.get("aside", ""),
                )
                titles += table_of_content_content.safe_substitute(
                    title=slide.get("title", "(image)"),
                    id=slide_html_index
                )
                class_name = "content-slide image-only-slide"

            elif slide_type == "cards":
                cards_html = ""
                for card in slide.get("cards", []):
                    cards_html += card_template.safe_substitute(
                        title=card.get("title", ""),
                        content=card.get("content", "")
                    )
                section_content = cards_content.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=slide.get("title", ""),
                    cards=cards_html,
                    aside=slide.get("aside", ""),
                )
                titles += table_of_content_content.safe_substitute(
                    title=slide.get("title", ""),
                    id=slide_html_index
                )
                class_name = "cards-slide"

            else:
                continue

            slides_html += section.safe_substitute(
                index=str(slide_html_index),
                class_name=class_name,
                content=section_content,
            )

        if last_subtitle:
            table_of_content += table_of_content_subtitle.safe_substitute(
                title=last_subtitle,
                titles=titles,
                id=last_subtitle_index
            )

        return template.safe_substitute(
            description=self.data.get("description", ""),
            keywords=", ".join(self.data.get("keywords", [])),
            title=self.data.get("title", ""),
            default_icon=self.data.get("default icon", ""),
            default_icon_alt=self.data.get("default icon alt", ""),
            table_of_content=table_of_content,
            slides=slides_html,
            author=self.data.get("author", ""),
            code_popup=code_popup_html.safe_substitute(),
        )

    def preview_html(self) -> None:
        html = self.build_html()
        tmp = NamedTemporaryFile(
            delete=False,
            suffix=".html",
            mode="w",
            encoding="utf-8"
        )
        tmp.write(html)
        tmp.close()
        webopen(f"file://{tmp.name}")

    def preview_html(self) -> None:
        html = self.build_html()
        self._preview_dir = TemporaryDirectory()
        preview_dir = self._preview_dir.name
        html_dir = join(preview_dir, "preview")
        html_path = join(html_dir, "preview.html")
        mkdir(html_dir)

        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)

        base_dir = dirname(abspath(__file__))
        copy2(join(base_dir, "styles.css"), join(preview_dir, "styles.css"))
        copy2(join(base_dir, "script.js"), join(preview_dir, "script.js"))
        webopen(f"file://{html_path}")

    def get_actual_slide_index(self, listbox_index: int) -> int:
        if not self.filtered_slide_indexes:
            return listbox_index
        return self.filtered_slide_indexes[listbox_index]

    def filter_slides(self, *_):
        query = self.slide_search_var.get().lower().strip()

        self.slides_listbox.delete(0, END)
        self.filtered_slide_indexes = []

        for i, slide in enumerate(self.data.get("slides", [])):
            title = slide.get("title", "").lower()
            slide_type = slide.get("type", "")

            label = SLIDE_TYPE_LABELS.get(slide_type, slide_type)

            text = f"{i+1}: [{label}] {slide.get('title','')}"

            if not query or query in title or query in label:
                self.slides_listbox.insert(END, text)
                self.filtered_slide_indexes.append(i)

        if self.slides_listbox.size() > 0:
            self.slides_listbox.selection_set(0)
            self.slides_listbox.activate(0)

    def validate_slides(self) -> None:
        warnings = []
        invalid_indexes = set()

        for index, slide in enumerate(self.data["slides"], start=1):
            title = slide.get("title", "").strip()
            if not title:
                warnings.append(f"Slide {index}: missing title")
                invalid_indexes.add(index - 1)

            if slide["type"] in ("content", "content-left"):
                if not slide.get("texts"):
                    warnings.append(f"Slide {index}: no content")
                    invalid_indexes.add(index - 1)
                if not slide.get("image"):
                    warnings.append(f"Slide {index}: no image")
                    invalid_indexes.add(index - 1)

            if slide["type"] == "image-only":
                if not slide.get("image"):
                    warnings.append(f"Slide {index}: no image")
                    invalid_indexes.add(index - 1)

            if slide["type"] == "cards":
                cards = slide.get("cards", [])
                if not cards:
                    warnings.append(
                        f"Slide {index}: no cards"
                    )
                    invalid_indexes.add(index - 1)
                for card in cards:
                    if not card.get("title", "").strip():
                        warnings.append(
                            f"Slide {index}: card without title"
                        )
                    if not card.get("content", "").strip():
                        warnings.append(
                            f"Slide {index}: card without content"
                        )

        if invalid_indexes:
            self.refresh_slide_colors(invalid_indexes)
            first_invalid = min(invalid_indexes)
            self.focus_slide(first_invalid)

        if warnings:
            showwarning("Validation", "\n".join(warnings))
        else:
            showinfo("Validation", "No issue detected.")

    def estimate_slide_duration(self, slide: dict) -> int:
        slide_type = slide.get("type", "")
        if slide_type == "title":
            return 10
        if slide_type == "image-only":
            return 15
        if slide_type == "cards":
          words = 0
          for card in slide.get("cards", []):
              words += len(card.get("title", "").split())
              words += len(card.get("content", "").split())
          reading_time = (words / 110) * 60
          return max(20, round(reading_time * 2))

        words = 0
        for block in slide.get("texts", []):
            content = block.get("content", "")

            if isinstance(content, str):
                words += len(content.split())
            elif isinstance(content, list):
                for item in content:
                    words += len(item.split())

        reading_time = (words / 110) * 60
        explanation_factor = 2.0
        duration = reading_time * explanation_factor
        return max(15, round(duration))

    def get_total_duration(self) -> int:
        return sum(
            self.estimate_slide_duration(s)
            for s in self.data.get("slides", [])
        )

    def format_duration(self, seconds: int) -> str:
        minutes = seconds // 60
        sec = seconds % 60
        return f"{minutes}m {sec}s"

    def update_progress(self) -> None:
        slides = self.data.get("slides", [])
        total = len(slides)

        if total == 0:
            self.progress_label.config(text="Progress: 0% | 0m")
            return

        current = self.slides_listbox.curselection()
        current_index = current[0] if current else 0

        percent = int((current_index + 1) / total * 100)

        total_time = self.get_total_duration()
        current_time = sum(
            self.estimate_slide_duration(s)
            for s in slides[:current_index + 1]
        )

        self.progress_label.config(
            text=(
                f"Progress: {percent}% | "
                f"{self.format_duration(current_time)} / "
                f"{self.format_duration(total_time)} "
                f"| remaining {self.format_duration(self.get_remaining_duration())}"
            )
        )

    def refresh_slide_colors(self, invalid_indexes):
        self.slides_listbox.itemconfig(0, background="#1e1e1e")

        for i in range(self.slides_listbox.size()):
            self.slides_listbox.itemconfig(
                i,
                bg="#1e1e1e",
                fg="#dd8a12"
            )

        for i in invalid_indexes:
            self.slides_listbox.itemconfig(
                i,
                bg="#4a1010",
                fg="#ff7070"
            )

    def on_slide_list_up(self, event=None):
        count = self.slides_listbox.size()
        if count == 0:
            return "break"

        selection = self.slides_listbox.curselection()
        if not selection:
            index = count - 1
        elif selection[0] == 0:
            index = count - 1
        else:
            index = selection[0] - 1

        self.focus_slide(index)
        return "break"

    def on_slide_list_down(self, event=None):
        count = self.slides_listbox.size()
        if count == 0:
            return "break"

        selection = self.slides_listbox.curselection()
        if not selection:
            index = 0
        elif selection[0] == count - 1:
            index = 0
        else:
            index = selection[0] + 1

        self.focus_slide(index)
        return "break"

    def update_title(self) -> None:
        title = self.data.get("title", "").strip()
        count = len(self.data.get("slides", []))
        if title:
            self.root.title(
                f"Slide Editor - {title} ({count} slides)"
            )
        else:
            self.root.title(
                f"Slide Editor ({count} slides)"
            )

    def get_remaining_duration(self) -> int:
        slides = self.data.get("slides", [])
        current = self.slides_listbox.curselection()
        idx = current[0] if current else 0
        return sum(
            self.estimate_slide_duration(s)
            for s in slides[idx:]
        )

    def sync_section_selection(self):
        selection = self.slides_listbox.curselection()
        if not selection:
            return

        slide_index = selection[0]
        current_section = 0
        for i, section_slide in enumerate(self.section_indexes):
            if section_slide <= slide_index:
                current_section = i
            else:
                break

        self.section_listbox.selection_clear(0, END)
        self.section_listbox.selection_set(current_section)
        self.section_listbox.see(current_section)

    def mark_modified(self, event: Event = None) -> None:
        self.modified = True

    def on_close(self) -> None:
        if self.modified:
            if not askokcancel("Unsaved Changes", "There are unsaved changes. Continue without saving?"):
                return
        self.root.destroy()

    def add_keyword_entry(self) -> None:
        entry = Entry(self.keyword_frame, bg="#1e1e1e", fg="#dd8a12", insertbackground="#dd8a12")
        entry.pack(fill="x", pady=2)
        entry.bind("<KeyRelease>", self.keyword_entry_updated)
        entry.bind("<KeyRelease>", self.mark_modified, add="+")
        self.keyword_entries.append(entry)

    def keyword_entry_updated(self, event: Event) -> None:
        for entry in self.keyword_entries:
            if not entry.get().strip():
                break
        else:
            self.add_keyword_entry()

    def new_file(self) -> None:
        self.file_path = None
        self.data = self.get_default_data()
        for key in self.entries:
            self.entries[key].delete(0, END)
        for entry in self.keyword_entries:
            entry.destroy()
        self.keyword_entries.clear()
        self.add_keyword_entry()
        self.slides_listbox.delete(0, END)
        self.modified = False

    def load_file(self) -> None:
        path = askopenfilename(filetypes=[("JSON Files", "*.json")])
        if not path:
            return
        try:
            with open(path, "r") as f:
                self.data = load(f)
            self.populate_fields()
        except Exception as e:
            showerror("Error", f"Could not load file:\n{e}")
        else:
            self.file_path = path
            self.modified = False

    def save_file(self) -> None:
        if not self.file_path:
            path = asksaveasfilename(defaultextension=".json", filetypes=[("JSON Files", "*.json")])
            if not path:
                return
            self.file_path = path
        self.update_data_from_fields()
        try:
            with open(self.file_path, "w") as f:
                dump(self.data, f, indent=4)
        except Exception as e:
            showerror("Error", f"Could not save file:\n{e}")
        else:
            showinfo("Saved", "File saved successfully!")
            self.modified = False

    def generate_slides(self) -> None:
        """Generate the HTML file from current data."""
        if not self.export_path:
            path = asksaveasfilename(defaultextension=".html", filetypes=[("HTML Files", "*.html")])
            if not path:
                return
            self.export_path = path

        self.update_data_from_fields()

        slides_html = ""
        titles = ""
        last_subtitle = ""
        last_subtitle_index = 3
        table_of_content = ""

        for index, slide in enumerate(self.data["slides"]):
            slide_html_index = index + 3
            slide_type = slide["type"]
            icon_alt   = slide.get("icon alt", self.data.get("default icon alt", ""))
            image_alt  = slide.get("image alt", "")

            if slide_type in ("content", "content-left"):
                texts_html = ""
                for text in slide.get("texts", []):
                    if text["type"] == "p":
                        texts_html += paragraph.safe_substitute(content=text["content"])
                    else:
                        list_content = "".join(
                            list_element.safe_substitute(content=el)
                            for el in text["content"]
                        )
                        if text["type"] == "ul":
                            texts_html += bullet_points.safe_substitute(list_content=list_content)
                        elif text["type"] == "ol":
                            texts_html += ordered_list.safe_substitute(list_content=list_content)

                has_code = bool(slide.get("code", "").strip())
                btn_html = ""
                if has_code:
                    btn_html = code_button_template.safe_substitute(
                        code=escape(slide["code"]),
                        lang=slide.get("code lang", "")
                    )

                tpl = content_image_left if slide_type == "content-left" else content
                section_content = tpl.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=slide.get("title", ""),
                    text=texts_html,
                    aside=slide.get("aside", ""),
                    image=slide.get("image", ""),
                    image_alt=image_alt,
                    code_button=btn_html,
                )
                titles += table_of_content_content.safe_substitute(
                    title=slide["title"], id=slide_html_index
                )
                class_name = "content-slide"

            elif slide_type == "title":
                if last_subtitle:
                    table_of_content += table_of_content_subtitle.safe_substitute(
                        title=last_subtitle, titles=titles, id=last_subtitle_index
                    )
                    titles = ""
                last_subtitle = slide.get("title", "")
                last_subtitle_index = slide_html_index
                section_content = subtitle.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=last_subtitle,
                )
                class_name = "subtitle-slide"

            elif slide_type == "image-only":
                section_content = content_image_only.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=slide.get("title", ""),
                    image=slide.get("image", ""),
                    image_alt=image_alt,
                    aside=slide.get("aside", ""),
                )
                titles += table_of_content_content.safe_substitute(
                    title=slide.get("title", "(image)"), id=slide_html_index
                )
                class_name = "content-slide image-only-slide"

            elif slide_type == "cards":
                cards_html = ""
                for card in slide.get("cards", []):
                    cards_html += card_template.safe_substitute(
                        title=card.get("title", ""),
                        content=card.get("content", "")
                    )
                section_content = cards_content.safe_substitute(
                    icon=slide.get("icon", ""),
                    icon_alt=icon_alt,
                    title=slide.get("title", ""),
                    cards=cards_html,
                    aside=slide.get("aside", ""),
                )
                titles += table_of_content_content.safe_substitute(
                    title=slide.get("title", ""),
                    id=slide_html_index
                )
                class_name = "cards-slide"

            else:
                continue

            slides_html += section.safe_substitute(
                index=str(slide_html_index),
                class_name=class_name,
                content=section_content,
            )

        if last_subtitle:
            table_of_content += table_of_content_subtitle.safe_substitute(
                title=last_subtitle, titles=titles, id=last_subtitle_index
            )

        file_content = template.safe_substitute(
            description=self.data.get("description", ""),
            keywords=", ".join(self.data.get("keywords", [])),
            title=self.data.get("title", ""),
            default_icon=self.data.get("default icon", ""),
            default_icon_alt=self.data.get("default icon alt", "MauriceLambert icon"),
            table_of_content=table_of_content,
            slides=slides_html,
            author=self.data.get("author", ""),
            code_popup=code_popup_html.safe_substitute(),
        )

        try:
            with open(self.export_path, "w", encoding="utf-8") as f:
                f.write(file_content)
        except Exception as e:
            showerror("Error", f"Could not generate file:\n{e}")
        else:
            showinfo("Generated", "File generated successfully!")

        self._generate_notes_file()

    def _generate_notes_file(self) -> None:
        """Generate the companion notes HTML file alongside the presentation."""
        if not self.export_path:
            return

        notes_path = join(
            dirname(self.export_path),
            splitext(basename(self.export_path))[0] + "_notes.html"
        )

        slides_data = [
            {
                "title": self.data.get("title", "Présentation"),
                "notes": [],
            },
            {
                "title": "Table des matières",
                "notes": [],
            }
        ]

        for slide in self.data.get("slides", []):
            slides_data.append({
                "title": slide.get("title", ""),
                "notes": slide.get("notes", []),
            })

        slides_data.append({
            "title": "My path, my passion: cybersecurity",
            "notes": [],
        })

        slides_json = dumps(slides_data, ensure_ascii=False, indent=2)
        notes_content = notes_template.safe_substitute(notes=slides_json)

        try:
            with open(notes_path, "w", encoding="utf-8") as f:
                f.write(notes_content)
        except Exception as e:
            showerror("Error", f"Could not generate notes file:\n{e}")
            return

        showinfo("Generated", f"Slides + notes generated!\nNotes: {basename(notes_path)}")


    def populate_fields(self) -> None:
        scroll_pos = self.slides_listbox.yview()[0]

        for key in self.entries:
            self.entries[key].delete(0, END)
            self.entries[key].insert(0, self.data.get(key, ""))

        for entry in self.keyword_entries:
            entry.destroy()

        self.keyword_entries.clear()
        for keyword in self.data.get("keywords", []):
            entry = Entry(self.keyword_frame, bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e", insertbackground="#dd8a12")
            entry.insert(0, keyword)
            entry.pack(fill="x", pady=2)
            entry.bind("<KeyRelease>", self.keyword_entry_updated)
            entry.bind("<KeyRelease>", self.mark_modified, add="+")
            self.keyword_entries.append(entry)

        self.add_keyword_entry()
        self.slides_listbox.delete(0, END)
        for idx, slide in enumerate(self.data.get("slides", [])):
            label = SLIDE_TYPE_LABELS.get(slide["type"], slide["type"])
            title = slide.get("title", "")
            self.slides_listbox.insert(END, f"{idx+1}: [{label}] {title}")

        self.section_listbox.delete(0, END)
        self.section_indexes.clear()
        for idx, slide in enumerate(self.data.get("slides", [])):
            if slide.get("type") == "title":
                self.section_listbox.insert(
                    END,
                    slide.get("title", "(untitled)")
                )
                self.section_indexes.append(idx)

        self.update_title()
        self.update_progress()
        self.slides_listbox.yview_moveto(scroll_pos)

    def jump_to_section(self, event=None):
        selection = self.section_listbox.curselection()
        if not selection:
            return

        section_index = selection[0]
        slide_index = self.section_indexes[section_index]
        self.slides_listbox.selection_clear(0, END)
        self.slides_listbox.selection_set(slide_index)
        self.slides_listbox.activate(slide_index)
        self.slides_listbox.see(slide_index)
        self.update_progress()

    def update_data_from_fields(self) -> None:
        for key in self.entries:
            self.data[key] = self.entries[key].get()
        self.data["keywords"] = [
            e.get() for e in self.keyword_entries if e.get().strip()
        ]

    def add_slide_dialog(self) -> None:
        dialog = Toplevel(self.root)
        dialog.title("Add Slide")
        dialog.geometry("340x340")
        dialog.configure(bg="#2e2e2e")

        Label(dialog, text="Position", bg="#2e2e2e", fg="#dd8a12").pack(pady=5)
        position_var = IntVar(value=len(self.data["slides"]) + 1)
        Entry(dialog, textvariable=position_var, bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e", insertbackground="#dd8a12").pack(fill="x", padx=10)

        Label(dialog, text="Type", bg="#2e2e2e", fg="#dd8a12").pack(pady=5)
        type_var = StringVar(value="content")
        type_frame = Frame(dialog, bg="#2e2e2e")
        type_frame.pack(pady=5)
        for label_text, value in SLIDE_TYPES:
            Radiobutton(
                type_frame, text=label_text, variable=type_var, value=value,
                bg="#2e2e2e", fg="#dd8a12", selectcolor="#1e1e1e",
                activebackground="#2e2e2e", activeforeground="#dd8a12",
            ).pack(anchor="w", padx=10)

        def submit() -> None:
            try:
                pos = int(position_var.get())
                if not (1 <= pos <= len(self.data["slides"]) + 1):
                    raise ValueError
            except ValueError:
                showerror("Invalid", "Position must be a valid number.")
                return

            slide_type = type_var.get()
            slide = {
                "type": slide_type,
                "icon": self.data["default icon"],
                "icon alt": self.data["default icon alt"],
                "title": "",
                "notes": [],
            }
            if slide_type in ("content", "content-left"):
                slide.update({
                    "aside": self.data["default aside"],
                    "image": "",
                    "image alt": "",
                    "texts": [],
                    "code": "",
                    "code lang": "",
                })
            elif slide_type == "image-only":
                slide.update({
                    "aside": self.data["default aside"],
                    "image": "",
                    "image alt": "",
                })
            elif slide_type == "cards":
                slide.update({
                    "aside": self.data["default aside"],
                    "cards": [],
                })

            self.update_data_from_fields()
            self.data["slides"].insert(pos - 1, slide)
            self.populate_fields()

            self.focus_slide(pos - 1)
            self.open_slide_editor(
                self.data["slides"][pos - 1],
                pos - 1
            )

            # self.slides_listbox.select_clear(0, END)
            # self.slides_listbox.select_set(pos - 1)
            # self.slides_listbox.activate(pos - 1)

            dialog.destroy()
            self.modified = True

        Button(dialog, text="Add Slide", command=submit, bg="#1e1e1e", fg="#dd8a12",
               activebackground="#444444", activeforeground="#dd8a12").pack(pady=10)

    def focus_slide(self, index: int) -> None:
        self.slides_listbox.selection_clear(0, END)
        self.slides_listbox.selection_set(index)
        self.slides_listbox.activate(index)
        self.slides_listbox.see(index)
        self.update_progress()

    def edit_selected_slide(self) -> None:
        selection = self.slides_listbox.curselection()
        if not selection:
            showwarning("No selection", "Please select a slide to edit.")
            return

        real_index = self.get_actual_slide_index(selection[0])
        self.open_slide_editor(self.data["slides"][real_index], real_index)

    def remove_selected_slide(self) -> None:
        selection = self.slides_listbox.curselection()

        if not selection:
            showwarning("No selection", "Please select a slide to remove.")
            return

        real_index = self.get_actual_slide_index(selection[0])
        slide = self.data["slides"][real_index]

        if not askokcancel("Delete slide", f'Delete "{slide.get("title", "(untitled)")}" ?'):
            return

        del self.data["slides"][real_index]

        self.populate_fields()

        if self.data["slides"]:
            self.focus_slide(
                min(real_index, len(self.data["slides"]) - 1)
            )

        self.modified = True

    def move_slide_up(self) -> None:
        selection = self.slides_listbox.curselection()
        if not selection:
            return
        real_index = self.get_actual_slide_index(selection[0])

        target = (
            len(self.data["slides"]) - 1
            if real_index == 0
            else real_index - 1
        )
        self.data["slides"][real_index], self.data["slides"][target] = (
            self.data["slides"][target], self.data["slides"][real_index]
        )
        self.populate_fields()
        self.focus_slide(target)
        self.modified = True

    def move_slide_down(self) -> None:
        selection = self.slides_listbox.curselection()
        if not selection:
            return
        real_index = self.get_actual_slide_index(selection[0])

        target = (
            0
            if i == len(self.data["slides"]) - 1
            else i + 1
        )
        self.data["slides"][real_index], self.data["slides"][target] = (
            self.data["slides"][target], self.data["slides"][real_index]
        )
        self.populate_fields()
        self.focus_slide(target)
        self.modified = True

    def open_slide_editor(
        self,
        slide: Dict[str, Union[List[Dict[str, str]], str]],
        index: int = None,
    ) -> None:
        """Manage slide edition GUI and data."""

        unsaved_slide = False

        def modify(event: Event = None) -> None:
            nonlocal unsaved_slide
            unsaved_slide = True

        dialog = Toplevel(self.root)
        title = slide.get("title", "").strip()
        if index is not None:
            dialog.title(f"#{index + 1} - {title or 'Untitled'}")
        else:
            dialog.title(title or "Edit Slide")
        dialog.geometry("640x660")
        dialog.configure(bg="#2e2e2e")

        slide_type = slide["type"]
        TAB_NAMES = ["Metadata", "Content", "Notes"]
        active_tab = StringVar(value="Metadata")

        tab_bar = Frame(dialog, bg="#1e1e1e")
        tab_bar.pack(fill="x", padx=0, pady=0)

        Frame(dialog, bg="#444444", height=1).pack(fill="x")

        body = Frame(dialog, bg="#2e2e2e")
        body.pack(fill="both", expand=True)

        button_frame = Frame(dialog, bg="#2e2e2e")
        button_frame.pack(fill="x", padx=10, pady=8, side="bottom")

        tab_frames: Dict[str, Frame] = {}
        tab_buttons: Dict[str, Button] = {}

        def show_tab(name: str) -> None:
            active_tab.set(name)
            for n, f in tab_frames.items():
                f.pack_forget()
            tab_frames[name].pack(fill="both", expand=True)
            for n, b in tab_buttons.items():
                if n == name:
                    b.configure(bg="#2e2e2e", fg="#dd8a12", relief="flat",
                                borderwidth=0, padx=12, pady=6)
                else:
                    b.configure(bg="#1e1e1e", fg="#888888", relief="flat",
                                borderwidth=0, padx=12, pady=6)

        for name in TAB_NAMES:
            f = Frame(body, bg="#2e2e2e")
            tab_frames[name] = f
            b = Button(
                tab_bar, text=name,
                command=lambda n=name: show_tab(n),
                bg="#1e1e1e", fg="#888888",
                activebackground="#2e2e2e", activeforeground="#dd8a12",
                relief="flat", borderwidth=0, padx=12, pady=6,
                font=("Courier New", 10),
            )
            b.pack(side="left")
            tab_buttons[name] = b

        Frame(dialog, bg="#444444", height=1).pack(fill="x")
        button_frame = Frame(dialog, bg="#2e2e2e")
        button_frame.pack(fill="x", padx=10, pady=8, side="bottom")

        meta_frame = tab_frames["Metadata"]

        if slide_type in ("content", "content-left", "image-only"):
            simple_fields = ("icon", "icon alt", "title", "image", "image alt", "aside")
        elif slide_type == "cards":
            simple_fields = ("icon", "icon alt", "title", "aside")
        else:
            simple_fields = ("icon", "icon alt", "title")

        fields: Dict[str, Entry] = {}
        for field in simple_fields:
            Label(meta_frame, text=field.capitalize(), bg="#2e2e2e", fg="#dd8a12").pack(anchor="w")
            entry = Entry(meta_frame, bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e", insertbackground="#dd8a12")
            entry.insert(0, slide.get(field, ""))
            entry.bind("<KeyRelease>", modify)
            entry.pack(fill="x")
            fields[field] = entry
        fields = {}
        for widget in meta_frame.winfo_children():
            widget.destroy()
        for field in simple_fields:
            Label(meta_frame, text=field.capitalize(), bg="#2e2e2e", fg="#dd8a12",
                  font=("Courier New", 10)).pack(anchor="w", padx=10, pady=(6, 0))
            entry = Entry(meta_frame, bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e",
                          insertbackground="#dd8a12", font=("Courier New", 10))
            entry.insert(0, slide.get(field, ""))
            entry.bind("<KeyRelease>", modify)
            entry.pack(fill="x", padx=10)
            fields[field] = entry

        content_tab = tab_frames["Content"]
        texts: Dict[str, tuple] = {}
        code_lang_entry = None
        code_text_widget = None

        if slide_type in ("content", "content-left"):
            scroll_frame = ScrollableFrame(content_tab)
            scroll_frame.pack(fill="both", expand=True, pady=10)
            text_container = scroll_frame.scrollable_frame

            Label(text_container, text="Texts", bg="#2e2e2e", fg="#dd8a12", font=("Courier New", 10)).pack(anchor="w", padx=10, pady=(8, 2))

            def add_text_block(text_data: Dict[str, str] = None, _modify: bool = True):
                nonlocal unsaved_slide
                if _modify:
                    unsaved_slide = True

                text_type = StringVar(value=(text_data["type"] if text_data else "p"))
                frame = Frame(text_container, bg="#1e1e1e")
                frame.pack(fill="x", pady=4, padx=6)

                type_frame = Frame(frame, bg="#1e1e1e")
                type_frame.pack(fill="x")
                for t_human, t_html in [("paragraph", "p"), ("bullet points", "ul"), ("ordered list", "ol")]:
                    Radiobutton(
                        type_frame, text=t_human, variable=text_type, value=t_html,
                        bg="#1e1e1e", fg="#dd8a12", selectcolor="#2e2e2e", font=("Courier New", 10)
                    ).pack(side="left")

                content_frame = Frame(frame, bg="#2e2e2e")
                content_frame.pack(fill="both")
                content_widget = []

                def render_content_widget() -> None:
                    for w in content_frame.winfo_children():
                        w.destroy()
                    nonlocal content_widget
                    content_widget = []

                    if text_type.get() == "p":
                        text = Text(content_frame, height=3, bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e", insertbackground="#dd8a12", font=("Courier New", 10))
                        if text_data and text_data["type"] == "p":
                            text.insert("1.0", text_data["content"])
                        text.pack(fill="x", padx=4, pady=2)
                        content_widget = text
                    else:
                        entries = []
                        initial = (
                            text_data["content"]
                            if text_data and isinstance(text_data["content"], list)
                            else [""]
                        )
                        for item in initial:
                            e = Entry(content_frame, bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e", insertbackground="#dd8a12", font=("Courier New", 10))
                            e.insert(0, item)
                            e.pack(fill="x", padx=4, pady=2)
                            entries.append(e)

                        def check_to_add_new(event: Event, last_entry: Entry) -> None:
                            if last_entry.get() and last_entry == entries[-1]:
                                ne = Entry(content_frame, bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e", insertbackground="#dd8a12", font=("Courier New", 10))
                                ne.pack(fill="x", padx=4, pady=2)
                                ne.bind("<KeyRelease>", lambda ev: check_to_add_new(ev, ne))
                                entries.append(ne)
                            nonlocal unsaved_slide
                            unsaved_slide = event is not None

                        if entries:
                            entries[-1].bind("<KeyRelease>", lambda ev: check_to_add_new(ev, entries[-1]))
                        check_to_add_new(None, entries[-1])
                        content_widget = entries

                    texts[text_type._name] = (text_type, content_widget)

                text_type.trace_add("write", lambda *_: render_content_widget())
                render_content_widget()
                scroll_frame._on_frame_configure()
                scroll_frame._on_canvas_configure()

            for block in slide.get("texts", []):
                add_text_block(block, False)

            Button(content_tab, text="+ Add Text Block", command=add_text_block,
                   bg="#1e1e1e", fg="#dd8a12", activebackground="#444444",
               activeforeground="#dd8a12", font=("Courier New", 10),
               relief="flat").pack(anchor="w", padx=10, pady=6)

            Frame(meta_frame, bg="#444444", height=1).pack(fill="x", padx=10, pady=4)
            Label(meta_frame, text="Code popup (optional)",
                  bg="#2e2e2e", fg="#dd8a12", font=("Courier New", 10)).pack(anchor="w", padx=10)
            Label(meta_frame, text="Language (e.g. python, bash, c)",
                  bg="#2e2e2e", fg="#666666", font=("Courier New", 9)).pack(anchor="w", padx=10)
            code_lang_entry = Entry(meta_frame, bg="#1e1e1e", fg="#dd8a12",
                                    insertbackground="#dd8a12", font=("Courier New", 10))
            code_lang_entry.insert(0, slide.get("code lang", ""))
            code_lang_entry.bind("<KeyRelease>", modify)
            code_lang_entry.pack(fill="x", padx=10, pady=2)

            Label(meta_frame, text="Code",
                  bg="#2e2e2e", fg="#666666", font=("Courier New", 9)).pack(anchor="w", padx=10)
            code_text_widget = Text(meta_frame, height=10, bg="#1e1e1e", fg="#00ff00",
                                    insertbackground="#00ff00", font=("Courier New", 10))
            code_text_widget.insert("1.0", slide.get("code", ""))
            code_text_widget.bind("<KeyRelease>", modify)
            code_text_widget.pack(fill="both", expand=True, padx=10, pady=2)
        elif slide_type == "cards":
            card_widgets = []
            scroll_frame = ScrollableFrame(content_tab)
            scroll_frame.pack(fill="both", expand=True, pady=10)
            text_container = scroll_frame.scrollable_frame
            Label(text_container, text="Cards", bg="#2e2e2e", fg="#dd8a12", font=("Courier New", 10)).pack(anchor="w", padx=10, pady=(8, 2))

            def add_card(card_data=None):
                nonlocal unsaved_slide
                unsaved_slide = True
                frame = Frame(text_container, bg="#1e1e1e")
                frame.pack(fill="x", padx=6, pady=6)
                Label(frame, text="Card title", bg="#1e1e1e", fg="#dd8a12").pack(anchor="w")
                title_entry = Entry(frame, bg="#111111", fg="#dd8a12", insertbackground="#dd8a12")
                title_entry.pack(fill="x", pady=2)
                Label(frame, text="Content", bg="#1e1e1e", fg="#dd8a12").pack(anchor="w")
                content_text = Text(frame, height=5, bg="#111111", fg="#dd8a12", insertbackground="#dd8a12")
                content_text.pack(fill="x", pady=2)
                if card_data:
                    title_entry.insert(0, card_data.get("title", ""))
                    content_text.insert("1.0", card_data.get("content", ""))
                card_widgets.append((title_entry, content_text))

            for card in slide.get("cards", []):
                add_card(card)

            Button(content_tab, text="+ Add Card", command=add_card, bg="#1e1e1e", fg="#dd8a12").pack(anchor="w", padx=10, pady=10)
        else:
            Label(content_tab,
                  text="No editable content for this slide type.",
                  bg="#2e2e2e", fg="#666666", font=("Courier New", 10)).pack(pady=40)

        notes_tab = tab_frames["Notes"]
        note_entries: List[Entry] = []
        notes_scroll = ScrollableFrame(notes_tab)
        notes_scroll.pack(fill="both", expand=True)
        notes_container = notes_scroll.scrollable_frame

        Label(notes_container, text="Speaker notes",
              bg="#2e2e2e", fg="#dd8a12", font=("Courier New", 10)).pack(anchor="w", padx=10, pady=(8, 2))
        Label(notes_container,
              text="One entry per note point. New entry appears automatically.",
              bg="#2e2e2e", fg="#666666", font=("Courier New", 9)).pack(anchor="w", padx=10, pady=(0, 6))

        def add_note_entry(value: str = "", _modify: bool = True) -> None:
            nonlocal unsaved_slide
            if _modify:
                unsaved_slide = True
            e = Entry(notes_container, bg="#1e1e1e", fg="#dd8a12", selectbackground="#dd8a12", selectforeground="#1e1e1e",
                      insertbackground="#dd8a12", font=("Courier New", 10))
            e.insert(0, value)
            e.pack(fill="x", padx=10, pady=2)
            note_entries.append(e)

            def on_key(event: Event) -> None:
                nonlocal unsaved_slide
                unsaved_slide = True
                if e.get().strip() and e == note_entries[-1]:
                    add_note_entry(_modify=True)
                notes_scroll._on_frame_configure()

            e.bind("<KeyRelease>", on_key)

        for note in slide.get("notes", []):
            add_note_entry(note, _modify=False)
        add_note_entry(_modify=False)

        def save() -> None:
            nonlocal unsaved_slide

            for field, entry in fields.items():
                slide[field] = entry.get().strip()

            if slide_type in ("content", "content-left"):
                new_texts = []
                for t_type, cw in texts.values():
                    if t_type.get() == "p":
                        c = cw.get("1.0", "end").strip()
                        if c:
                            new_texts.append({"type": "p", "content": c})
                    else:
                        c = [e.get().strip() for e in cw if e.get().strip()]
                        if c:
                            new_texts.append({"type": t_type.get(), "content": c})

                slide["texts"] = new_texts
                slide["code"] = code_text_widget.get("1.0", "end").strip()
                slide["code lang"] = code_lang_entry.get().strip()
            elif slide_type == "cards":
                slide["cards"] = []
                for title_entry, content_text in card_widgets:
                    title = title_entry.get().strip()
                    content = (content_text.get("1.0", "end").strip())
                    if title or content:
                        slide["cards"].append({"title": title, "content": content})

            slide["notes"] = [e.get().strip() for e in note_entries if e.get().strip()]

            self.populate_fields()
            self.modified = True
            unsaved_slide = False
            dialog.destroy()

        Button(button_frame, text="Save Slide", command=save,
           bg="#1e1e1e", fg="#dd8a12",
           activebackground="#444444", activeforeground="#dd8a12",
           font=("Courier New", 10)).pack(side="left", padx=5)

        def on_close_dialog() -> None:
            if unsaved_slide:
                if not askokcancel("Unsaved Slide", "This slide has unsaved changes. Close anyway?"):
                    return
            dialog.destroy()

        dialog.protocol("WM_DELETE_WINDOW", on_close_dialog)

if __name__ == "__main__":
    root = Tk()
    app = SlideGeneratorApp(root)
    root.mainloop()
